### ISSUE TITLE
Using different binary versions in different terminals

### ISSUE THREAD

**Issue by rgoldberg** [7mind/binlink#5]
Does binlink support using different binary versions in different terminals?

e.g., if sdkman is setup to use Kotlin 1.4.10 by default, sdkman supports using Kotlin 1.4.0 in one terminal (without affecting other terminals) via running `sdk use kotlin 1.4.0` in that terminal. In that terminal's `$PATH`, sdkman replaces the path to Kotlin 1.4.10 with the path to 1.4.0. The `$PATH`s of all other terminals, including those created in the future, are unaffected.

If binlink doesn't yet support this, you could implement this by, on each new terminal creation, creating a new subdirectory in the system temp directory, then prepending that in front of the main binlink symlink directory's path in the new terminal's `$PATH`. Terminal-specific version selections could be made by creating the correct symlink in this terminal-specific temp directory.

**Comment by pshirshov** [comment]
Currently that's not supported (I just made a dirty prototype), though this can be easily achieved by using an env variable pointing to a config name. E.g. `BINLINK_CONFIG_BASE="alternative.toml"` and/or `BINLINK_CONFIG="local.toml"`  may be used to change base/local configs. 

Your idea with separate binlink folder makes another nice option as well.

I'll add this eventually, thanks for the idea.

**Comment by rgoldberg** [comment]
Thanks for replying.

Can you explain how the `$BINLINK_CONFIG*` env vars would enable per-terminal bin versions?

I haven't read your code (I don't even know Rust), nor have I used binlink yet, so I'm not too knowledgeable about how it works.

I thought binlink just adds a single directory to `$PATH`, and, in that directory, creates symlinks to executables depending on what version of the third-party software you want to use.

How could config env vars change what executable versions are used?

**Comment by pshirshov** [comment]
here is a local configuration file and a global one. When user runs a symlinked binary, `binlink` makes several lookups through the configs and determines which actual executable should be started. In case there is no match it falls back to standard `$PATH` lookup. Once target binary is found `binlink` just performs `execve` call.

Both the configs can be overridden with `BINLINK_LOCAL_CONFIG_NAME`  and `BINLINK_BASE_CONFIG_PATH` since `0.0.4`. So, now you may, for example, have several local configs and choose which to use by exporting `BINLINK_LOCAL_CONFIG_NAME`.

> I don't even know Rust

It's not like I know Rust 😺
